### ISSUE TITLE
Max number of RTT attach retries exceeded

### ISSUE THREAD

**Issue by hamptokr** [knurling-rs/app-template#12]
I followed the defmt setup guide from [this post](https://ferrous-systems.com/blog/defmt/) and finished the todos. However I get the following when running the `hello` example. The repo is here: https://github.com/hamptokr/voltron-testing
```sh
  (HOST) INFO  flashing program
  (HOST) INFO  success!
────────────────────────────────────────────────────────────────────────────────
  (HOST) ERROR Max number of RTT attach retries exceeded.
Error: RTT control block not found in target memory. Make sure RTT is initialized on the target.
```

Here are some versions of things I am using

- `cargo 1.46.0 (149022b1d 2020-07-17)`
- `rustc 1.46.0 (04488afe3 2020-08-24)`
- `stm32f4xx-hal = { version = "0.8.3", features = ["rt", "stm32f429"] }`
- `probe-run 0.1.3` (from master branch)

**Comment by hamptokr** [comment]
After more research and debugging I believe there is a hardware issue with the external memory on the eval board I had. This can probably be ignored.

**Comment by jonas-schievink** [comment]
Okay, closing this then. If you see this problem again and think it's a bug in our tools, please open a new issue. Thanks!
