### ISSUE TITLE
Linked blog post has security issues

### ISSUE THREAD

**Issue by drahnr** [knurling-rs/app-template#3]
![image](https://user-images.githubusercontent.com/667047/91543339-b6991d80-e91e-11ea-89e5-67bd75acc37e.png)

**Comment by Xylakant** [comment]
Thanks for the heads up. This may be a transient issue with netlify (our host), maybe while renewing the certificate. If that issue persist for you, I'd be interested in what version of FF you're using. A problem with SNI may result in such an error.

**Comment by drahnr** [comment]
It works fine now...
