### ISSUE TITLE
vscode error `can't find crate for `test``

### ISSUE THREAD

**Issue by YoshieraHuang** [knurling-rs/app-template#55]
Hi. After I used `app-template` to generate a project and opened it with vscode, the rust extension emitted an error `can't find crate for test`. Could you tell me how to avoid this.

**Comment by Urhengulas** [comment]
Hi @YoshieraHuang,

This error occurs if you run `cargo check` or `cargo run` with the `--all-targets` flag. It should be possible to build the binaries using the `--bin` option.

I didn't try it, but adding following options to your `.vscode/settings.json` seems to solve the problem ([link](https://github.com/rust-lang/vscode-rust/issues/729#issuecomment-635977755)):
```json
{
    "rust-analyzer.cargo.target": "thumbv7em-none-eabihf",
    "rust-analyzer.checkOnSave.allTargets": false
}
```

Does it solve your problem?

**Comment by YoshieraHuang** [comment]
> Hi @YoshieraHuang,
> 
> This error occurs if you run `cargo check` or `cargo run` with the `--all-targets` flag. It should be possible to build the binaries using the `--bin` option.
> 
> I didn't try it, but adding following options to your `.vscode/settings.json` seems to solve the problem ([link](https://github.com/rust-lang/vscode-rust/issues/729#issuecomment-635977755)):
> 
> ```json
> {
>     "rust-analyzer.cargo.target": "thumbv7em-none-eabihf",
>     "rust-analyzer.checkOnSave.allTargets": false
> }
> ```
> 
> Does it solve your problem?

Thank you for your nice reply. Unfortunately, it seems that the `rust-analyzer` settings in `.vscode/setting.json` is never applied in my project. I used the 'Rust' extension rather than `rust-analyzer` extension.

**Comment by YoshieraHuang** [comment]
Known the reason is vscode setting, I try to figure out the corresponding setting in 'Rust' extension. These settings may be equivalent to traditional `rust-analyzer` settings:
```json
{
    "rust.all_targets": false,
    "rust.target": "thumbv7em-none-eabihf"
}
```
but the error still emits.

**Comment by Urhengulas** [comment]
Please either comment on the upstream issue (https://github.com/rust-lang/vscode-rust/issues/729) or open a new issue.

Or just switch to `rust-analyzer` 😉 

Hope you can resolve it!
