### ISSUE TITLE
error[E0463]: can't find crate for `test`

### ISSUE THREAD

**Issue by Crzyrndm** [knurling-rs/app-template#62]
Have been trying to retrofit defmt::test to a library. Ran into issues, thought I'd better start with something working
Ran through the readme instructions (`cargo rb hello` builds and runs)
`cargo test` just complains about "can't find crate test`
![image](https://user-images.githubusercontent.com/8765278/155867401-18569689-dfb6-4938-b65e-089d869ae89d.png)
Other than readme instructions for device specific bits, no modifications have been made

installed cargo tools
![image](https://user-images.githubusercontent.com/8765278/155867441-de035d71-5aad-4c76-bb7b-7ddf511d8d8a.png)

**Comment by Crzyrndm** [comment]
Reading through more, noticed that the README here has `cargo test --lib` and `cargo test --test <test name>` which *do* work

Docs for the test crate do not appear to include this (see https://docs.rs/crate/defmt-test/0.3.0), A bit of a trip hazard?

**Comment by Urhengulas** [comment]
Hi @Crzyrndm, thank you for reporting. It seems like we should make our documention a bit more clear here.
